---

- name: Get apim code
  git:
    repo: https://github.com/waltermoreira/apim
    dest: /home/apim/apim
    update: yes
  sudo: yes
  sudo_user: apim
  notify:
    - rebuild containers

- name: Install all Python requirements
  pip: requirements=/home/apim/apim/dev_requirements.txt
  sudo: yes

- name: Patch swagger ui
  lineinfile:
    dest: /usr/local/lib/python2.7/dist-packages/flask_restful_swagger/html.py
    regexp: "^(.*)docExpansion:(.*)$"
    line: '\1docExpansion: "full"'
    state: present
    backrefs: yes
  sudo: yes