---

- name: Get apim code
  git:
    repo: https://github.com/waltermoreira/apim
    dest: /home/apim/apim
    version: "{{ branch | default(master) }}"
    update: yes
  sudo: yes
  sudo_user: apim
  notify:
    - Rebuild containers
    - Reload apim server

- name: Install all Python requirements
  pip: requirements=/home/apim/apim/dev_requirements.txt
  sudo: yes

- set_fact: swagger_html="/usr/local/lib/python2.7/dist-packages/flask_restful_swagger/html.py"
  when: ansible_os_family == "Debian"

- set_fact: swagger_html="/usr/lib/python2.7/site-packages/flask_restful_swagger/html.py"
  when: ansible_os_family == "RedHat"

- name: Patch swagger ui
  lineinfile:
    dest: "{{ swagger_html }}"
    regexp: "^(.*)docExpansion:(.*)$"
    line: '\1docExpansion: "full"'
    state: present
    backrefs: yes
  sudo: yes

- name: Setup local config file
  ini_file:
    dest: /home/apim/.apim.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  sudo: yes
  sudo_user: apim
  with_items: config
  notify: Document local config file

- name: Make sure the apim server is started
  debug: msg="(should implement this)"

- name: Reload apim server
  shell: test -f /var/run/apim_server.pid && kill -HUP `cat /var/run/apim_server.pid`
  sudo: yes
  ignore_errors: yes
