FROM ubuntu:15.04

RUN DEBIAN_FRONTEND="noninteractive" \
    apt-get update -y && \
    apt-get install -y python python-dev python-pip
RUN pip install pika==0.9.14 ipython

ADD adama /adama

ENV RABBITMQ_SERVER localhost:6379

WORKDIR /adama
