---


- name: Update apt cache once a day
  apt: upgrade=dist update_cache=yes cache_valid_time=84600
  sudo: yes

- name: Install zlib
  apt: name=zlib1g-dev state=present
  sudo: yes

- name: Install crypto libraries
  apt: name="{{ item }}" state=present
  sudo: yes
  with_items:
    - libffi-dev
    - libssl-dev
    - make
    - g++

- name: Install git in Debian
  apt: name=git state=present
  sudo: yes

- name: Install libncurses in Debian
  apt: name=libncurses5-dev state=present
  sudo: yes

- name: Install supervisor in Debian
  apt: name=supervisor state=latest
  sudo: yes

- name: Ensure supervisor is running in Debian
  service: name=supervisor state=started
  sudo: yes

- name: Ensure Python 2.7 installation
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - python
    - python-dev

- name: Install pip from PyPi bootstrap script
  shell: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" && python get-pip.py "pip<8"
  sudo: yes

- name: Install PyOpenSSL
  pip: name=pyOpenSSL state=latest
  sudo: yes

