---

- name: Update apt cache once a day
  apt: update_cache=yes cache_valid_time=84600
  sudo: yes

- name: Install zlib
  apt: name=zlib1g-dev state=present
  sudo: yes

- name: Install crypto libraries
  apt: name="{{ item }}" state=present
  sudo: yes
  with_items:
    - libffi-dev
    - libssl-dev

- name: Install git in Debian
  apt: name=git state=present
  sudo: yes

- name: Install libncurses in Debian
  apt: name=libncurses5-dev state=present
  sudo: yes

- name: Install supervisor in Debian
  apt: name=supervisor state=latest
  sudo: yes

- name: Ensure supervisor is running in Debian
  service: name=supervisor state=started
  sudo: yes
