---

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Add user adama
  user: name=adama generate_ssh_key=yes state=present
  sudo: yes

- name: Add public keys to access user adama
  authorized_key:
    user: adama
    key: "{{ lookup('file', item) }}"
    state: present
  with_fileglob:
    - public_keys/*.pub
  sudo: yes

- name: Add user adama to sudoers with no password
  lineinfile:
    dest: /etc/sudoers.d/99-adama-user
    line: 'adama ALL=(ALL) NOPASSWD:ALL'
    state: present
    create: yes
  sudo: yes

- name: Make sure old user 'apim' is deleted
  user: name=apim state=absent remove=yes
  sudo: yes

- name: Ensure permissions on adama sudoers
  file:
    path: /etc/sudoers.d/99-adama-user
    mode: 0440
  sudo: yes
