---

- name: Install git in Redhat
  yum: name=git state=latest
  sudo: yes

- name: Install libncurses in Redhat
  yum: name=ncurses-devel state=latest
  sudo: yes

- name: Install supervisor in Redhat
  yum: name=supervisor state=latest
  sudo: yes

- name: Ensure supervisor is running in Redhat
  service: name=supervisord state=started
  sudo: yes