---

- name: Rebuild containers
  command: make adapters
  args:
    chdir: /home/adama/adama
  sudo: yes
  sudo_user: adama

- name: Document local config file
  lineinfile:
    dest: /home/adama/.adama.conf
    insertbefore: BOF
    line: "# Managed by ansible\n# See all options in $ADAMA_SRC/adama.conf\n# Tweak automatically configured values in $ADAMA_SRC/ansible/host_vars/<this_host>\n"
    state: present
  sudo: yes
  sudo_user: adama

- name: Force supervisor to reload configs
  command: supervisorctl update
  sudo: yes

- name: Reload adama server
  supervisorctl: name=adama state=restarted
  sudo: yes
