---
# handlers file for nginx

- name: Make sure nginx is running
  service:
    name: nginx
    state: started
  sudo: yes

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
  sudo: yes
