# Common image for all containers

FROM ubuntu:14.04.4
ENV HOME /root

RUN apt-get update
RUN apt-get install -y build-essential software-properties-common python-software-properties libssl-dev libffi-dev
