---

- set_fact:
    swagger_html="/usr/local/lib/python2.7/dist-packages/flask_restful_swagger/html.py"
    supervisord_conf_dir="/etc/supervisor/conf.d"
    supervisord_conf_ext="conf"
    supervisord_service="supervisor"
    pip_executable="/usr/local/bin/pip" 
  when: ansible_os_family == "Debian"

- set_fact:
    swagger_html="/usr/local/lib/python2.7/site-packages/flask_restful_swagger/html.py"
    supervisord_conf_dir="/etc/supervisord.d"
    supervisord_conf_ext="ini"
    supervisord_service="supervisord"
    pip_executable="/usr/local/bin/pip"
  when: ansible_os_family == "RedHat"

- name: Get adama code
  git:
    repo: https://github.com/Arabidopsis-Information-Portal/adama.git
    dest: /home/adama/adama
    #version: "{{ branch | default(master) }}"
    update: yes
    force: yes
  sudo: yes
  sudo_user: adama
  register: got_adama
  notify:
    - Build base containers

- name: Get adamalib
  git:
    repo: https://github.com/Arabidopsis-Information-Portal/adamalib.git
    dest: /home/adama/adamalib
    update: yes
    force: yes
  sudo: yes
  register: got_adamalib
  sudo_user: adama

- name: Ensure netns directory
  file:
    path: /var/run/netns
    state: directory
  sudo: yes

- name: Install support libraries for provenance
  apt: name={{ item }} state=latest
  sudo: yes
  with_items:
    - libxml2-dev
    - libxslt1-dev
    - graphviz
    - zlib1g-dev

- name: Install all Python requirements
  pip:
    requirements: /home/adama/adama/requirements.txt
    executable: "{{ pip_executable }}"
    state: present
  when: got_adama|changed
  sudo: yes
  ignore_errors: yes

- name: Install adama itself
  command: python setup.py develop
  args:
    chdir: /home/adama/adama
  when: got_adama|changed
  sudo: yes

- name: Install adamalib
  command: python setup.py develop
  args:
    chdir: /home/adama/adamalib
  when: got_adamalib|changed
  sudo: yes

- name: Patch swagger ui
  lineinfile:
    dest: "{{ swagger_html }}"
    regexp: "^(.*)docExpansion:(.*)$"
    line: '\1docExpansion: "full"'
    state: present
    backrefs: yes
  sudo: yes

- name: Setup local config file
  ini_file:
    dest: /etc/adama.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  sudo: yes
  with_items: "{{ config }}"
  notify: Document local config file

- name: Setup monitor config file
  ini_file:
    dest: /home/adama/adama/bin/monitor.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  sudo: yes
  with_items: "{{ monitor }}"
  notify: Document monitor config file

- name: Setup backup config file
  ini_file:
    dest: /home/adama/adama/bin/backup.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  sudo: yes
  with_items: "{{ autobackup }}"
  notify: Document backup config file

- name: Add adama to supervisor
  template:
    src=adama.ini.j2
    dest={{ supervisord_conf_dir }}/adama.{{ supervisord_conf_ext }}
    force=yes
  sudo: yes
  notify:
    - Force supervisor to reload configs
    - Reload adama server

- name: Install crontab for backup job
  cron:
    name: backup
    job: /home/adama/adama/bin/backup.py
    user: root
    state: present
    special_time: daily
  sudo: yes

- name: Install crontab for monitor task
  cron:
    name: monitor
    job: "/home/adama/adama/bin/monitor.py > /dev/null 2>&1"
    user: root
    minute: 15
    state: present
  sudo: yes
