---

- name: Get adama code
  git:
    repo: https://github.com/waltermoreira/adama
    dest: /home/adama/adama
    version: "{{ branch | default(master) }}"
    update: yes
  sudo: yes
  sudo_user: adama
  notify:
    - Rebuild containers
    - Reload adama server

- name: Install all Python requirements
  pip: requirements=/home/adama/adama/dev_requirements.txt
  sudo: yes

- set_fact: swagger_html="/usr/local/lib/python2.7/dist-packages/flask_restful_swagger/html.py"
  when: ansible_os_family == "Debian"

- set_fact: swagger_html="/usr/lib/python2.7/site-packages/flask_restful_swagger/html.py"
  when: ansible_os_family == "RedHat"

- name: Patch swagger ui
  lineinfile:
    dest: "{{ swagger_html }}"
    regexp: "^(.*)docExpansion:(.*)$"
    line: '\1docExpansion: "full"'
    state: present
    backrefs: yes
  sudo: yes

- name: Setup local config file
  ini_file:
    dest: /home/adama/.adama.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  sudo: yes
  sudo_user: adama
  with_items: config
  notify: Document local config file

- name: Make sure the adama server is started
  command: adama_server.py
  args:
    chdir: /home/adama/adama/bin
    creates: /var/run/adama_server.pid
  sudo: yes
  environment:
    HOME: /home/adama
