---

- set_fact:
    swagger_html="/usr/local/lib/python2.7/dist-packages/flask_restful_swagger/html.py"
    supervisord_conf_dir="/etc/supervisor/conf.d"
    supervisord_conf_ext="conf"
    supervisord_service="supervisor"
    pip_executable="/usr/local/bin/pip"
  when: ansible_os_family == "Debian"

- set_fact:
    swagger_html="/usr/local/lib/python2.7/site-packages/flask_restful_swagger/html.py"
    supervisord_conf_dir="/etc/supervisord.d"
    supervisord_conf_ext="ini"
    supervisord_service="supervisord"
    pip_executable="/usr/local/bin/pip"
  when: ansible_os_family == "RedHat"

- name: Install support libraries for provenance
  apt: name={{ item }} state=latest
  sudo: yes
  with_items:
    - libxml2-dev
    - libxslt1-dev
    - graphviz
    - zlib1g-dev

- name: Get adama code
  git:
    repo: https://github.com/Arabidopsis-Information-Portal/adama.git
    dest: /home/adama/adama
    version: "{{ branch | default(master) }}"
    update: yes
  sudo: yes
  sudo_user: adama
  register: got_adama
  notify:
    - Rebuild containers
    - Reload adama server

- name: Ensure netns directory
  file:
    path: /var/run/netns
    state: directory
  sudo: yes

- name: Install all Python requirements
  pip:
    requirements: /home/adama/adama/requirements.txt
    executable: "{{ pip_executable }}"
  when: got_adama|changed
  sudo: yes

- name: Install adama itself
  command: python setup.py develop
  args:
    chdir: /home/adama/adama
  when: got_adama|changed
  sudo: yes

- name: Patch swagger ui
  lineinfile:
    dest: "{{ swagger_html }}"
    regexp: "^(.*)docExpansion:(.*)$"
    line: '\1docExpansion: "full"'
    state: present
    backrefs: yes
  sudo: yes

- name: Setup local config file
  ini_file:
    dest: /etc/adama.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  sudo: yes
  with_items: config
  notify: Document local config file

- name: Add adama to supervisor
  template:
    src=adama.ini.j2
    dest={{ supervisord_conf_dir }}/adama.{{ supervisord_conf_ext }}
  sudo: yes
  notify:
    - Force supervisor to reload configs
    - Reload adama server

- name: Make sure the adama server is started
  supervisorctl: name=adama state=started
  sudo: yes

- name: Install crontab for backup job
  cron:
    name: backup
    job: /home/adama/adama/bin/backup.py
    user: root
    special_time: hourly
  sudo: yes
