---

- name: Clone swagger-ui
  git:
    repo: https://github.com/swagger-api/swagger-ui.git
    dest: /home/adama/swagger-ui
    update: yes
  sudo: yes
  sudo_user: adama
  register: clone_swagger_ui

- name: Add Adama modifications to swagger-ui
  copy:
    src: "{{ item.src }}"
    dest: "/home/adama/swagger-ui/{{ item.dest }}"
  sudo: yes
  sudo_user: adama
  with_items:
    - { src: 'index.html', dest: 'dist/index.html' }
    - { src: 'gulpfile.js', dest: 'gulpfile.js' }
  register: adama_swagger_ui

- name: Rebuild swagger-ui image
  docker_image:
    path: /home/adama/swagger-ui
    name: swagger-ui-builder
    state: build
  sudo: yes
  sudo_user: adama
  when: clone_swagger_ui|changed or adama_swagger_ui|changed
  register: rebuild_swagger_ui

- name: Ensure old container is removed
  docker:
    image: swagger-ui-builder
    name: swagger_ui
    state: absent
  sudo: yes
  sudo_user: adama
  when: rebuild_swagger_ui|changed

- name: Ensure swagger-ui is running
  docker:
    image: swagger-ui-builder
    name: swagger_ui
    state: running
    expose: 8080
    ports: "9000:8080"
  sudo: yes
  sudo_user: adama
