---

# Name of the image we are deploying.
image_name: serfnode

# Uncomment this variable and set a domain or ip of a registry to use
# for exchanging images.  Use your username at hub.docker.com to use
# the Docker hub.
#
# remote_registry: localhost

# Define the exposed ports of the app.  These ports get mapped to
# random ports in the host, which can be queried by sending a "where"
# message to the serfnode.  Use 'mapped_ports' for a deterministic
# mapping.
exposed_ports:
  - 1234
  - 7000
  - 8000
mapped_ports:
  - "8000:8000"

# Name of the container for the serfnode.
serfnode_name: test

# Role of the serfnode (to be queried via serf events) (str).
my_role: my_role

# ip of a peer in the cluster (ip)
peer:

# own advertised ip. Defaults to the ip of the interface that can
# access the internet (ip)
ip:

# ip of the service this node provides. Defaults to its own ip,
# but it can differ if the node is acting as a proxy (ip)
service_ip:

# port of the ip this node provides (int)
service_port:

# port where the serf agent is listening (int)
serf_port:

# port where the serf agent accepts commands (int)
rpc_port:

# list of volumes to mount in the application container ([str])
# For example:
# app_volumes:
#   - /tmp:/foo
#   - /bin:/bar
app_volumes:

# list of containers from where to mount volumes in the application
# container ([str])
# For example:
# app_volumes_from:
#   - containerA
app_volumes_from:

# whether the container will run in privileged mode
privileged: no
