---

- set_fact: bashrc="bash.bashrc"

- name: Ensure vim installation
  apt: name=vim state=present
  sudo: yes

- name: Ensure Python 2.7 installation
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - python
    - python-dev
    - python-pip

- name: Install ack-grep
  apt: name=ack-grep state=present
  sudo: yes

- name: Install tmux
  apt: name=tmux state=present
  sudo: yes

- name: Install other tools
  apt: name={{ item }} state=present
  with_items:
    - curl
    - htop
  sudo: yes

- name: Make sure there is a gitconfig
  copy:
    src: gitconfig
    dest: /home/adama/.gitconfig
    owner: adama
  sudo: yes