---

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "Redhat"

- name: Make vim the default editor for everyone
  lineinfile:
    dest: /etc/{{ bashrc }}
    insertafter: EOF
    line: export EDITOR=vim
    state: present
  sudo: yes

- name: Setup tmux
  copy:
    src: tmux.conf
    dest: /etc/tmux.conf
  sudo: yes