---

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Make vim the default editor for everyone
  lineinfile:
    dest: /etc/{{ bashrc }}
    insertafter: EOF
    line: export EDITOR=vim
    state: present
  sudo: yes

- name: Setup tmux
  copy:
    src: tmux.conf
    dest: /etc/tmux.conf
  sudo: yes

- name: Ensure there is a ipython config directory
  file:
    path: /home/adama/.ipython/profile_default
    state: directory
  sudo: yes
  sudo_user: adama

- name: Setup config file for ipython
  lineinfile:
    dest: /home/adama/.ipython/profile_default/ipython_config.py
    create: yes
    line: "{{ item }}"
    state: present
  sudo: yes
  sudo_user: adama
  with_items:
    - "c = get_config()"
    - "c.InteractiveShellApp.exec_lines = []"
    - "c.InteractiveShellApp.exec_lines.append(\"%load_ext autoreload\")"
    - "c.InteractiveShellApp.exec_lines.append(\"%autoreload 2\")"
    - "c.InteractiveShellApp.exec_lines.append(r\"\"\"print(\"\\n-- Autoreload extension activated\")\"\"\")"