---
# tasks file for registrator

- name: Copy sources to remote
  copy:
    src: registrator
    dest: /root
  sudo: yes

- name: Ensure correct mode in notebook.sh
  file:
    path: /root/registrator/app/notebook.sh
    mode: a+x
  sudo: yes

- name: Build image
  docker_image:
    name: adama/registrator
    path: /root/registrator
    state: present
  sudo: yes

- name: Run the container
  docker:
    image: adama/registrator
    name: registrator_1
    state: started
    expose:
      - 8888
    ports:
      - "9999:8888"
    command: /app/notebook.sh
    links:
      - redis_1:redis
      - rabbit_1:rabbit
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/root/registrator:/local/registrator"
  sudo: yes