---
# tasks file for rsyslog

- name: Packages are present
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
  with_items:
    - rsyslog
    - logrotate
  sudo: yes

- name: Config file is present
  template:
    src: 10-logstash.conf.j2
    dest: /etc/rsyslog.d/10-logstash.conf
  register: config_result
  notify: Restart rsyslog
  sudo: yes

