FROM python:3.4.3

ADD . /

{% for module in modules %}
WORKDIR /modules/{{ module }}
RUN pip install -r requirements.txt
ENV PYTHONPATH $PYTHONPATH:/modules/{{ module }}

{% endfor %}

WORKDIR /app
RUN pip install -r requirements.txt

