---
# tasks file for redis

- name: Ensure there is pip
  apt:
    name: python-pip
    state: present
  sudo: yes

- name: Ensure docker-py is installed
  pip:
    name: docker-py
    version: 1.2.3
    state: present
  sudo: yes

- name: Run redis
  docker:
    image: redis
    name: redis_1
    state: started
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
  sudo: yes