---
galaxy_info:
  author: Walter Moreira
  description: Ensure pip
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - utopic
        - vivid
dependencies: []
  
