---

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Add adama user to docker group
  user:
    name: adama
    append: yes
    groups: docker
  sudo: yes
