---

- name: Ensure redis server is installed
  apt: name=redis-server state=present
  sudo: yes
  when: ansible_os_family == "Debian"

- name: Ensure redis server is installed
  yum: name=redis state=latest
  sudo: yes
  when: ansible_os_family == "RedHat"

- set_fact: redis="redis-server"
  when: ansible_os_family == "Debian"

- set_fact: redis="redis"
  when: ansible_os_family == "RedHat"

- name: Ensure redis server is running
  service:
    name: "{{ redis }}"
    state: started
    enabled: yes
  sudo: yes

- name: Ensure redis is configured for using AOF
  lineinfile:
    dest: /etc/redis/redis.conf
    regexp: ^appendonly
    line: appendonly yes
  sudo: yes
  notify: Ensure redis is using AOF
